<a href="https://colab.research.google.com/github/Carlos-A-Palomares/mis433/blob/main/week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [32]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')


What's your name? Carlos
Welcome, Carlos!


In [34]:
# complete your program here
f = int(input('Please enter the temperature in Fahrenheit: '))

print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 30
30
30F is -1.1111111111111112 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [ ]:
# complete your program here
c = int(input('Please enter the temperature in Celcius: '))
print(c)

#Fahrenheit = (C*9/5)+32
f = (c * 9/5) + 32

print(f'{c}C is {f} in Fahrenheit. ')


Please enter the temperature in Celcius: 30
30
30C is 86.0 in Fahrenheit. 


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [ ]:
# complete your program here
d = int(input('Please enter the temperature: '))
m = input('Is this in Celsius or Fahrenheit? ').lower()
c = (d - 32) * 5/9
f = (d * 9/5) + 32
if m == 'c':
  print(f'{c}C is {d} in Farhrenheit')
elif m == 'f':
  print(f'{f}F is {d} in Celcius')




Please enter the temperature: 50
Is this in Celsius or Fahrenheit? c
10.0C is 50 in Farhrenheit


## Question 2

Have some fun with strings.

In [35]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [ ]:
# Find the length of this sentence.
len(sentence)

48

In [ ]:
# Convert the whole string to lower case.
print(sentence.lower())

talk is cheap. show me the code - linus torvalds


In [ ]:
# Extract a substring from the 10th character from left to the 10th character from right.
sentence[9:-9]

'heap. Show me the code - Linus'

In [ ]:
# Split the sentence into a list of substrings by space ' '.
sentence.split(" ")

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']

In [ ]:
# Given the sentence, output a list of words in lowercase (without punctuations).
sentence.lower().split()


['talk', 'is', 'cheap.', 'show', 'me', 'the', 'code', '-', 'linus', 'torvalds']

In [ ]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
vowels = 'aeiou'
count = 0
for v in vowels:
  if v in vowels:
    count += 1
print('The total number of vowels is', count)

The total number of vowels is 5


In [ ]:
# Find the positions (indexes) of all vowels in the sentence.
res = []
for i in range(len(sentence)):
  if sentence[i] in vowels:
    res.append(i)
print('The vowel indices are: '+ str(res))


The vowel indices are: [1, 5, 10, 11, 17, 21, 25, 28, 30, 35, 37, 41, 44]


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [ ]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []

for number in range(5):
    cubes.append(number * number * number)

print(cubes)

[0, 1, 8, 27, 64]


In [ ]:
# Use list comprehension to create the same list
cubes = [number * number * number for number in range(5)]
print(cubes)

[0, 1, 8, 27, 64]


In [ ]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
vowels = "aeiouAEIOU"

indexes = [index for index in range(len(sentence)) if sentence[index] in vowels]
print(indexes)

[1, 3, 6, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47, 54, 57, 59, 63, 66]


In [ ]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = input('How many numbers do you want? ')

n = int(n)

a = 0
b = 1

for number in range(n):
    fibonacci.append(a)
    a, b = b, a + b

print(fibonacci)


How many numbers do you want? 40
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [ ]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {
    "Pfizer": 0.95,
    "Moderna": 0.94,
    "Johnson & Johnson": 0.66
}

print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.94, 'Johnson & Johnson': 0.66}


In [ ]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(v_dict[v])


Which vaccine? Pfizer
0.95


In [ ]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict["Sputnik V"] = 0.914
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.94, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [ ]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict["Sinovac"] = 0.5038
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.94, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914, 'Sinovac': 0.5038}


In [ ]:
# Print vaccines with efficacy lower than 90%.
for vaccine in v_dict:
    if v_dict[vaccine] < 0.90:
        print(vaccine)

Johnson & Johnson
Sinovac


In [ ]:
# delete the Sinovac vaccine from the dictionary.
del v_dict["Sinovac"]
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.94, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [ ]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
# add your code here
for char in sentence:
    if char != ' ':
        if char in ch_dict:
            ch_dict[char] += 1
        else:
            ch_dict[char] = 1

# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [2]:
import numpy as np

In [3]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [4]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [5]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [6]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, (10, 10))
M.shape

(10, 10)

In [7]:
# Count the numbers in M with an absolute value greater than 1.
np.sum(np.abs(M) > 1)

np.int64(32)

In [8]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')

# Input the number of rows (input another integer >= 3)
c = input('column count: ')

# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, (int(r), int(c)))
arr

Row count: 30
column count: 25


array([[18, 16, 18, 18, 17, 13, 16, 11, 12, 19, 12, 14, 11, 11, 11, 16,
        10, 13, 16, 19, 18, 15, 19, 17, 14],
       [12, 12, 10, 11, 14, 15, 10, 18, 14, 14, 15, 12, 18, 15, 14, 15,
        10, 17, 14, 14, 15, 18, 12, 18, 15],
       [19, 17, 13, 14, 14, 17, 14, 16, 19, 18, 14, 14, 15, 19, 17, 11,
        18, 12, 14, 19, 10, 13, 17, 11, 10],
       [11, 17, 13, 18, 13, 11, 18, 12, 16, 16, 13, 11, 17, 11, 19, 12,
        11, 15, 17, 11, 19, 14, 12, 12, 11],
       [14, 18, 14, 19, 19, 13, 17, 19, 13, 12, 16, 11, 12, 10, 18, 14,
        15, 16, 13, 11, 12, 12, 13, 12, 10],
       [10, 15, 12, 19, 14, 16, 11, 13, 18, 12, 16, 11, 17, 15, 18, 14,
        19, 11, 17, 18, 13, 10, 13, 19, 15],
       [17, 19, 14, 12, 19, 14, 19, 13, 19, 16, 12, 18, 17, 13, 14, 15,
        17, 11, 16, 14, 18, 13, 12, 14, 11],
       [18, 19, 14, 11, 19, 14, 15, 10, 17, 14, 19, 18, 15, 16, 11, 18,
        16, 18, 19, 19, 17, 17, 13, 13, 12],
       [16, 15, 10, 17, 19, 18, 16, 14, 14, 19, 17, 13, 14, 13, 

In [9]:
# output the element in the first row and the third column
arr[0, 2]

np.int64(18)

In [10]:
# output the element in the second row and the last column
arr[1, -1]

np.int64(15)

In [11]:
# output the second row of the array
arr[1]

array([12, 12, 10, 11, 14, 15, 10, 18, 14, 14, 15, 12, 18, 15, 14, 15, 10,
       17, 14, 14, 15, 18, 12, 18, 15])

In [12]:
# output the second last row of the array
arr[-2]


array([14, 11, 19, 18, 16, 14, 15, 13, 12, 10, 17, 14, 15, 18, 19, 12, 15,
       12, 18, 12, 13, 14, 19, 12, 16])

In [13]:
# output the second column of the array
arr[:, 1]


array([16, 12, 17, 17, 18, 15, 19, 19, 15, 12, 19, 18, 19, 18, 18, 14, 13,
       14, 11, 11, 12, 17, 19, 15, 14, 10, 11, 11, 11, 15])

In [14]:
# output the second last column of the array
arr[:, -2]

array([17, 18, 11, 12, 12, 19, 14, 13, 17, 14, 15, 18, 14, 17, 16, 15, 18,
       13, 17, 17, 15, 18, 19, 17, 17, 15, 15, 10, 12, 11])

In [15]:
# output the upper-left 3x3 sub-array
arr[:3, :3]

array([[18, 16, 18],
       [12, 12, 10],
       [19, 17, 13]])

In [16]:
# output the bottom-left 3x3 sub-array
arr[-3:, :3]

array([[12, 11, 17],
       [14, 11, 19],
       [10, 15, 16]])

In [17]:
# output the upper-right 3x3 sub-array
arr[:3, -3:]

array([[19, 17, 14],
       [12, 18, 15],
       [17, 11, 10]])

In [18]:
# output the bottom-right 3x3 sub-array
arr[-3:, -3:]

array([[11, 10, 12],
       [19, 12, 16],
       [18, 11, 12]])

In [22]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.array(range(1, 51))

# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
A = A.reshape(5, 10)

A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [24]:
# add a row [51,...,60] to A
A = np.vstack((A, np.array(range(51, 61))))
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [25]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
# Re-initialize A to ensure correct dimensions before splitting
A = np.vstack((np.array(range(1, 51)).reshape(5, 10), np.array(range(51, 61))))

A1 = A[:3, :]
A2 = A[3:, :]

A1, A2

(array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]),
 array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]]))

In [26]:
# Add 10 to each element of A
A = A + 10

A

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [27]:
# Calculate the square root of each element in A
A = np.sqrt(A)

A

array([[3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
        4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558],
       [5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
        6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532],
       [6.40312424, 6.4807407 , 6.55743852, 6.63324958, 6.70820393,
        6.78232998, 6.8556546 , 6.92820323, 7.        , 7.07106781],
       [7.14142843, 7.21110255, 7.28010989, 7.34846923, 7.41619849,
        7.48331477, 7.54983444, 7.61577311, 7.68114575, 7.74596669],
       [7.81024968, 7.87400787, 7.93725393, 8.        , 8.06225775,
        8.1240384 , 8.18535277, 8.24621125, 8.30662386, 8.36660027]])

In [28]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [29]:
# Print the mean, standard devietion of all numbers in M
## Print the mean, standard devietion of all numbers in M
print(np.mean(M))
print(np.std(M))

0.1829515188893126
1.0374513585481053


In [30]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print(np.max(M))
print(np.percentile(M, 75))
print(np.median(M))
print(np.percentile(M, 25))
print(np.min(M))

3.0475231948261854
0.7558115335412169
0.058445206930582555
-0.5226639555274567
-2.3969924140387815
